# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'
  demands:
  - npm


variables:
  buildConfiguration: 'Release'
  wwwRootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotNetSdkVersion: '2.1.505'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 2.1.505'
  inputs:
    packageType: sdk
    version: '$(dotNetSdkVersion)'

- task: Npm@1
  displayName: 'Run Install NPM'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass $(wwwRootDir) --output $(wwwRootDir)'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinationName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info.'
  workingDirectory: '$(wwwRootDir)'

- task: DotNetCoreCli@2
  displayName: "Restore dependencies"
  inputs: 
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCli@2
  displayName: "Build dependencies"
  inputs: 
    command: 'build' 
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: '**/*.csproj'

- task: DotNetCoreCli@2
  displayName: "Publish project"
  inputs:
    command: 'publish'
    arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
    projects: '**/*.csproj'
    publishWebProjects: false
    zipAfterPublish: true

- task: DotNetCoreCli@2
  displayName: 'publish build artificacte'
  condition: 'succeeded()'
